#pragma once
#include "../Common/typedef.h"

  enum class eWeapon : uint8
  {
    GaussRifle = 0,
    GaussRifleJimRaynor = 1,
    C10CanisterRifle = 2,
    C10CanisterRifleSarahKerrigan = 3,
    FragmentationGrenade = 4,
    FragmentationGrenadeJimRaynor = 5,
    SpiderMines = 6,
    TwinAutocannons = 7,
    HellfireMissilePack = 8,
    TwinAutocannonsAlanSchezar = 9,
    HellfireMissilePackAlanSchezar = 10,
    ArcliteCannon = 11,
    ArcliteCannonEdmundDuke = 12,
    FusionCutter = 13,

    GeminiMissiles = 15,
    BurstLasers = 16,
    GeminiMissilesTomKazansky = 17,
    BurstLasersTomKazansky = 18,
    ATSLaserBattery = 19,
    ATALaserBattery = 20,
    ATSLaserBatteryHero = 21,
    ATALaserBatteryHero = 22,
    ATSLaserBatteryHyperion = 23,
    ATALaserBatteryHyperion = 24,
    FlameThrower = 25,
    FlameThrowerGuiMontag = 26,
    ArcliteShockCannon = 27,
    ArcliteShockCannonEdmundDuke = 28,
    LongboltMissile = 29,
    YamatoGun = 30,
    NuclearStrike = 31,
    Lockdown = 32,
    EMPShockwave = 33,
    Irradiate = 34,
    Claws = 35,
    ClawsDevouringOne = 36,
    ClawsInfestedKerrigan = 37,
    NeedleSpines = 38,
    NeedleSpinesHunterKiller = 39,
    KaiserBlades = 40,
    KaiserBladesTorrasque = 41,
    ToxicSpores = 42,
    Spines = 43,

    AcidSpore = 46,
    AcidSporeKukulza = 47,
    GlaveWurm = 48,
    GlaveWurmKukulza = 49,

    SeekerSpores = 52,
    SubterraneanTentacle = 53,
    SuicideInfestedTerran = 54,
    SuicideScourge = 55,
    Parasite = 56,
    SpawnBroodlings = 57,
    Ensnare = 58,
    DarkSwarm = 59,
    Plague = 60,
    Consume = 61,
    ParticleBeam = 62,

    PsiBlades = 64,
    PsiBladesFenix = 65,
    PhaseDisruptor = 66,
    PhaseDisruptorFenix = 67,

    PsiAssault = 69,
    PsionicShockwave = 70,
    PsionicShockwaveTZArchon = 71,

    DualPhotonBlasters = 73,
    AntiMatterMissiles = 74,
    DualPhotonBlastersMojo = 75,
    AntiMatterMissilesMojo = 76,
    PhaseDisruptorCannon = 77,
    PhaseDisruptorCannonDanimoth = 78,
    PulseCannon = 79,
    STSPhotonCannon = 80,
    STAPhotonCannon = 81,
    Scarab = 82,
    StasisField = 83,
    PsionicStorm = 84,
    WarpBladesZeratul = 85,
    WarpBladesHero = 86,

    PlatformLaserBattery = 92,
    IndependantLaserBattery = 93,

    TwinAutocannonsFloorTrap = 96,
    HellfireMissilePackWallTrap = 97,
    FlameThrowerWallTrap = 98,
    HellfireMissilePackFloorTrap = 99,

    NeutronFlare = 100,
    DisruptionWeb = 101,
    Restoration = 102,
    HaloRockets = 103,
    CorrosiveAcid = 104,
    MindControl = 105,
    Feedback = 106,
    OpticalFlare = 107,
    Maelstrom = 108,
    SubterraneanSpines = 109,

    WarpBlades = 111,
    C10CanisterRifleSamirDuran = 112,
    C10CanisterRifleInfestedDuran = 113,
    DualPhotonBlastersArtanis = 114,
    AntiMatterMissilesArtanis = 115,
    C10CanisterRifleAlexeiStukov = 116,

    None = 130
  };
